doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: '%env(resolve:DATABASE_DRIVER)%'
                host: '%env(resolve:DATABASE_HOST)%'
                dbname: '%env(resolve:DATABASE_DBNAME)%'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PWD)%'
                port: '%env(resolve:DATABASE_PORT)%'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                        

